export const services = [
  {
    slug: "tv-mounting",
    icon: "📺",
    title: "TV Mounting",
    short: "Clean, secure TV mounting with optional cable management.",
    hero: "Clean TV installation.",
    description: "Professional TV mounting for drywall, studs, concrete, brick, fireplaces, bedrooms, living rooms, and offices.",
    price: "From $89",
    time: "1–2 hours",
    difficulty: "Easy",
    materials: "Mount not included, cables optional",
    bullets: ["Wall mount installation", "Level and secure mounting", "Cable management options", "Soundbar mounting available"],
    heroImage: "/images/tv-mounting-1.jpg",
    images: [
      {
        src: "/images/tv-mounting-2.jpg",
        title: "Large TV Mounting",
        desc: "100-inch TV mounted on a tilting motion mount. The client can help lift the TV into place in 1-2 minutes, or an extra assistant can be arranged for +$50.",
        time: "1-1.5 hours",
        materials: "Tilting motion mount",
        price: "$150",
      },
      {
        src: "/images/tv-mounting-3.jpg",
        title: "Interactive Touch Screen TV",
        desc: "65-inch interactive touch screen TV mounted on a fixed mount. Installed by one person with no help needed from the client.",
        time: "1 hour",
        materials: "Fixed mount",
        price: "$100",
      },
      {
        src: "/images/tv-mounting-4.jpg",
        title: "Full Motion Mount",
        desc: "85-inch TV on a full motion mount for easy access to ports and cable connections.",
        time: "1-1.5 hours",
        materials: "Full motion mount",
        price: "$125",
      },
    ],
    reviews: [
      { text: "Nikita did a great job! Finished the task quickly and efficiently.", date: "Mar 30, 2026" },
      { text: "Nikita was fast and did an awesome job.", date: "Apr 19, 2026" },
      { text: "Quick and easy. Very professional and cleaned up after.", date: "Feb 24, 2026" },
    ],
    faqs: [
      { q: "What wall types do you mount on?", a: "Drywall, studs, concrete, brick, tile, and fireplace surrounds — we handle all of them." },
      { q: "Do you hide the cables?", a: "Yes, we offer in-wall cable concealment or surface cord covers for a clean, professional look." },
      { q: "How long does it take?", a: "Most TV mounts are done in 1–2 hours including setup and cleanup." },
      { q: "Do I need to supply the wall mount?", a: "Yes, the mount is not included. We recommend purchasing one rated for your TV size and weight before booking." },
      { q: "Can you mount above a fireplace?", a: "Yes, we mount over fireplaces regularly. We'll make sure the placement is safe and at a comfortable viewing height." },
      { q: "Can you mount a soundbar too?", a: "Absolutely — soundbar mounting can be added to any TV mount job for an extra fee." },
      { q: "What if I'm not sure which mount to buy?", a: "Send us a message with your TV model and wall type — we'll point you to the right mount before the visit." },
    ],
  },
  {
    slug: "furniture-assembly",
    icon: "🪑",
    title: "Furniture Assembly",
    short: "Beds, desks, dressers, cabinets, shelves, and outdoor furniture.",
    hero: "Furniture assembled right.",
    description: "Fast, clean furniture assembly for IKEA, Wayfair, Amazon, office furniture, bedroom sets, storage cabinets, and patio furniture.",
    price: "From $75",
    time: "1–3 hours",
    difficulty: "Easy",
    materials: "All hardware included in box",
    bullets: ["Beds and dressers", "Desks and office furniture", "Shelves and cabinets", "Patio furniture"],
    heroImage: "/images/furniture-2.jpg",
    images: [
      {
        src: "/images/furniture-1.jpg",
        title: "IKEA Wardrobe",
        desc: "Full IKEA PAX wardrobe assembled with interior organizers and sliding doors.",
        time: "2.5 hours",
        materials: "Hardware from box",
        price: "$150",
      },
      {
        src: "/images/furniture-3.jpg",
        title: "Office Desk Setup",
        desc: "L-shaped desk with hutch assembled and positioned for home office.",
        time: "1.5 hours",
        materials: "Hardware from box",
        price: "$110",
      },
      {
        src: "/images/furniture-4.jpg",
        title: "Bed Frame Assembly",
        desc: "King bed frame with headboard and slat system fully assembled.",
        time: "1.5 hours",
        materials: "Hardware from box",
        price: "$120",
      },
      {
        src: "/images/furniture-5.jpg",
        title: "Bookshelf & Cabinet",
        desc: "Billy bookcase and storage cabinet assembled and leveled.",
        time: "1 hour",
        materials: "Hardware from box",
        price: "$75",
      },
      {
        src: "/images/furniture-6.jpg",
        title: "Dresser Assembly",
        desc: "6-drawer dresser assembled with smooth-glide drawer test.",
        time: "1 hour",
        materials: "Hardware from box",
        price: "$85",
      },
      {
        src: "/images/furniture-7.jpg",
        title: "Patio Furniture Set",
        desc: "Outdoor dining table and 4 chairs assembled and arranged.",
        time: "2 hours",
        materials: "Hardware from box",
        price: "$130",
      },
      {
        src: "/images/furniture-8.jpg",
        title: "TV Console Assembly",
        desc: "Media console assembled with cable cutouts aligned.",
        time: "1 hour",
        materials: "Hardware from box",
        price: "$75",
      },
      {
        src: "/images/furniture-9.jpg",
        title: "Kids Room Set",
        desc: "Bunk bed with underbed storage assembled safely and tested.",
        time: "3 hours",
        materials: "Hardware from box",
        price: "$180",
      },
    ],
    reviews: [
      { text: "Great tasker! Worked hard, fast, independently, and attention to detail!", date: "Mar 11, 2026" },
      { text: "Nikita was great with furniture assembly — thorough and reliable.", date: "Mar 13, 2026" },
      { text: "Finished quickly and did a good job.", date: "Mar 21, 2026" },
    ],
    faqs: [
      { q: "Do you bring tools?", a: "Yes, we bring all necessary tools — drills, levels, screwdrivers. Just have the boxes ready." },
      { q: "What brands do you assemble?", a: "IKEA, Wayfair, Amazon, West Elm, Pottery Barn, Crate & Barrel, and more." },
      { q: "What if parts are missing?", a: "We'll document missing parts and help you contact the retailer for replacements." },
      { q: "Can you assemble multiple pieces in one visit?", a: "Yes — booking a multi-item visit is the best value. List everything you need assembled when you book." },
      { q: "Do you remove packaging and trash?", a: "We'll break down boxes and leave the area clean. Trash removal can be arranged on request." },
      { q: "Can you rearrange or move furniture too?", a: "Yes, we can help position and arrange pieces after assembly at no extra charge for light items." },
      { q: "What if the instructions are confusing or missing?", a: "No problem — we've assembled hundreds of pieces and can work without instructions on most major brands." },
    ],
  },
  {
    slug: "smart-home",
    icon: "🏠",
    title: "Smart Home",
    short: "Thermostats, smart locks, cameras, doorbells, and sensors.",
    hero: "Smart home setup made simple.",
    description: "Installation and setup for smart thermostats, Ring/Nest cameras, smart locks, smart doorbells, sensors, and connected home devices.",
    price: "From $79",
    time: "1–2 hours",
    difficulty: "Medium",
    materials: "Device provided by client",
    bullets: ["Smart thermostat install", "Camera and doorbell setup", "Smart lock installation", "Device connection help"],
    heroImage: "/images/smart-1.jpg",
    images: [
      {
        src: "/images/smart-2.jpg",
        title: "Nest Thermostat Install",
        desc: "Nest Learning Thermostat installed with C-wire adapter and full app setup.",
        time: "1 hour",
        materials: "C-wire adapter (if needed)",
        price: "$85",
      },
      {
        src: "/images/smart-3.jpg",
        title: "Ring Doorbell Setup",
        desc: "Ring Video Doorbell Pro mounted, wired, and fully configured with app.",
        time: "45 min",
        materials: "Mounting screws included",
        price: "$79",
      },
      {
        src: "/images/smart-4.jpg",
        title: "Smart Lock Install",
        desc: "Schlage Encode smart lock installed and paired with home app.",
        time: "1 hour",
        materials: "Included in lock box",
        price: "$89",
      },
      {
        src: "/images/smart-5.jpg",
        title: "Security Camera Mount",
        desc: "Arlo camera mounted at entry point with angle adjusted for full coverage.",
        time: "30 min",
        materials: "Mounting hardware included",
        price: "$79",
      },
      {
        src: "/images/smart-6.jpg",
        title: "Smart Switch Install",
        desc: "Lutron Caseta smart dimmer switch installed and linked to Alexa.",
        time: "30 min",
        materials: "Wire nuts included",
        price: "$79",
      },
      {
        src: "/images/smart-7.jpg",
        title: "Multi-Device Setup",
        desc: "Thermostat + doorbell + 2 cameras installed in one visit.",
        time: "2.5 hours",
        materials: "All devices by client",
        price: "$249",
      },
      {
        src: "/images/smart-8.jpg",
        title: "Garage Controller",
        desc: "myQ smart garage door controller installed and configured.",
        time: "45 min",
        materials: "Included in box",
        price: "$79",
      },
      {
        src: "/images/smart-9.jpg",
        title: "Smart Sensor Package",
        desc: "Motion and door sensors installed throughout home and linked to hub.",
        time: "1.5 hours",
        materials: "Adhesive mounts included",
        price: "$119",
      },
    ],
    reviews: [
      { text: "He came on time, got the task done and was very thorough. The price was very fair.", date: "May 9, 2025" },
      { text: "Helped me install a smart thermostat quickly and efficiently.", date: "Feb 24, 2026" },
      { text: "Nikita helped install our Ring devices, and he was exceptional. He was highly respectful of our property and came up with solutions on the spot.", date: "Feb 14, 2025" },
    ],
    faqs: [
      { q: "What brands do you install?", a: "Nest, Ring, Ecobee, August, Schlage, Arlo, Honeywell, Google Home, and more." },
      { q: "Do you help with the app setup?", a: "Yes, we fully configure the device and walk you through the app so you're comfortable using it." },
      { q: "Do I need a hub?", a: "Most modern smart devices work without a hub — we'll assess your setup and advise accordingly." },
      { q: "Can you install a smart thermostat if I have an older HVAC system?", a: "In most cases yes — we'll check your wiring first. Some older systems require a C-wire adapter which we can install." },
      { q: "Can you install multiple smart devices in one visit?", a: "Absolutely — that's actually the most efficient way. We can do thermostat, doorbell, and locks all in one trip." },
      { q: "What if my Wi-Fi doesn't reach the install location?", a: "We'll let you know during the visit. A mesh router or Wi-Fi extender may be needed for reliable performance." },
      { q: "Do you help if the device isn't working after install?", a: "Yes — we test everything before we leave and troubleshoot any connection issues on the spot." },
    ],
  },
  {
    slug: "handyman-repairs",
    icon: "🛠️",
    title: "Handyman",
    short: "Hourly handyman help for repairs, installs, and home fixes.",
    hero: "Whatever needs fixing — handled.",
    description: "Hourly handyman service for repairs, door hardware, shelving, fixtures, caulking, touch-ups, and general home maintenance. $70/hr with a 1-hour minimum.",
    price: "$70/hr",
    time: "1+ hours",
    difficulty: "Easy",
    materials: "Minimal — screws, anchors, caulk",
    bullets: ["Door hardware and alignment", "Shelving and mounting", "Fixtures and small repairs", "Caulking and touch-ups"],
    heroImage: "/images/repair-1.jpg",
    images: [
      { src: "/images/repair-2.jpg" },
      { src: "/images/repair-3.jpg" },
      { src: "/images/repair-5.jpg" },
    ],
    reviews: [
      { text: "Great communication and work. Highly recommend.", date: "Mar 20, 2026" },
      { text: "Did a great job with the baby gate and was fast with his work. Was friendly and I would recommend.", date: "Mar 15, 2026" },
      { text: "Nikita was excellent. He caulked my bathroom — shower, sink and toilet. The work was done fast and professionally.", date: "Mar 31, 2026" },
    ],
    faqs: [
      { q: "How does hourly pricing work?", a: "We charge $70/hr with a 1-hour minimum. Most small jobs wrap up in 1–2 hours — you only pay for the time it takes." },
      { q: "What's included in the hourly rate?", a: "Labor and standard hardware like screws, anchors, and caulk. Specialty materials or fixtures are extra — let us know when you book." },
      { q: "Can you tackle a list of repairs in one visit?", a: "Absolutely — knocking out a full list in one trip is the most efficient and cost-effective way to go." },
      { q: "Can you fix a door that won't close properly?", a: "Yes — door alignment, strike plate adjustment, and hinge tightening are common quick fixes we handle all the time." },
      { q: "Do you do caulking in bathrooms and kitchens?", a: "Yes, we re-caulk showers, sinks, tubs, and backsplashes. It's one of the most impactful small upgrades for a clean look." },
      { q: "Can you patch a small hole in drywall?", a: "Yes, small to medium holes are within our scope. We'll patch, sand, and leave it ready for paint." },
      { q: "Do you install curtain rods and blinds?", a: "Yes — curtain rods, blinds, and shades are quick installs we handle regularly." },
    ],
  },
  {
    slug: "electrical",
    icon: "⚡",
    title: "Electrical",
    short: "Outlets, switches, ceiling fans, light fixtures, and panel work.",
    hero: "Safe, clean electrical work.",
    description: "Professional electrical services for outlet and switch replacement, ceiling fan installation, light fixture upgrades, dimmer installation, and fixture swaps.",
    price: "From $79",
    time: "1–3 hours",
    difficulty: "Medium",
    materials: "Fixture provided by client",
    bullets: ["Outlet and switch replacement", "Ceiling fan installation", "Light fixture upgrades", "Dimmer and GFCI install"],
    heroImage: "/images/electrical-1.jpg",
    images: [
      {
        src: "/images/electrical-1.jpg",
        title: "Pendant Light Install",
        desc: "Three pendant lights installed over kitchen island with new junction boxes.",
        time: "2 hours",
        materials: "Fixtures by client, wire nuts",
        price: "$179",
      },
      {
        src: "/images/electrical-2.jpg",
        title: "Ceiling Fan Install",
        desc: "52\" Hunter ceiling fan installed in living room with remote control.",
        time: "1.5 hours",
        materials: "Brace kit, wire nuts",
        price: "$109",
      },
      {
        src: "/images/electrical-4.jpg",
        title: "Dimmer Switch Upgrade",
        desc: "Four standard switches replaced with Lutron Caseta dimmers.",
        time: "1 hour",
        materials: "Wire nuts, electrical tape",
        price: "$159",
      },
      {
        src: "/images/electrical-5.jpg",
        title: "Outlet Replacement",
        desc: "Outlet replaced with USB-C combo outlet in home office.",
        time: "20 min",
        materials: "Outlet plate included",
        price: "$79",
      },
      {
        src: "/images/electrical-6.jpg",
        title: "GFCI Install",
        desc: "GFCI outlet installed in bathroom to meet safety code requirements.",
        time: "30 min",
        materials: "GFCI outlet by client",
        price: "$79",
      },
      {
        src: "/images/electrical-7.jpg",
        title: "Chandelier Swap",
        desc: "Old chandelier removed and new 9-light fixture installed in dining room.",
        time: "1.5 hours",
        materials: "Canopy kit, wire nuts",
        price: "$129",
      },
      {
        src: "/images/electrical-8.jpg",
        title: "High Ceiling Fixture",
        desc: "New fixture installed on 20ft vaulted ceiling with ladder setup.",
        time: "2.5 hours",
        materials: "Extension rod, wire nuts",
        price: "$179",
      },
      {
        src: "/images/electrical-9.jpg",
        title: "Vanity Light Bar",
        desc: "Bathroom vanity light bar replaced with modern fixture above mirror.",
        time: "45 min",
        materials: "Fixture by client",
        price: "$89",
      },
      {
        src: "/images/electrical-10.jpg",
        title: "Outdoor Porch Light",
        desc: "Exterior porch light replaced and weatherproofed.",
        time: "45 min",
        materials: "Silicone sealant, wire nuts",
        price: "$89",
      },
      {
        src: "/images/electrical-11.jpg",
        title: "Exhaust Fan Install",
        desc: "Bathroom exhaust fan replaced with quiet Broan unit.",
        time: "1.5 hours",
        materials: "Included in fan box",
        price: "$109",
      },
      {
        src: "/images/electrical-12.jpg",
        title: "Under-Cabinet Lighting",
        desc: "LED strip lights installed under kitchen cabinets with dimmer.",
        time: "1.5 hours",
        materials: "LED strips by client, wire staples",
        price: "$119",
      },
      {
        src: "/images/electrical-13.jpg",
        title: "Multi-Room Switch Upgrade",
        desc: "6 standard switches replaced with smart switches throughout home.",
        time: "2.5 hours",
        materials: "Switches by client, wire nuts",
        price: "$249",
      },
    ],
    reviews: [
      { text: "Nikita was responsive, communicative, professional, skilled and quick. He did a quality job. I would book him again in a heartbeat.", date: "Mar 7, 2026" },
      { text: "I had a wonderful experience with Nikita! He showed up on time, kept things clean and explained everything before and after the job. Would definitely call him again.", date: "Mar 29, 2026" },
      { text: "Awesome awesome awesome. Super nice guy, very capable and did everything I needed to complete a very complex electrical task that was way over my head.", date: "Feb 20, 2026" },
      { text: "Nikita was great! Friendly, quick, and helpful. He installed our ceiling fan and chandelier.", date: "Mar 13, 2026" },
    ],
    faqs: [
      { q: "Can you install a ceiling fan where there's no existing fixture?", a: "Yes, we can add a new junction box and run the wiring as needed." },
      { q: "What's a GFCI outlet?", a: "A safety outlet required near water sources — bathrooms, kitchens, outdoors. We install and test them properly." },
      { q: "Can you replace a standard outlet with a USB outlet?", a: "Absolutely — USB combo outlets are a popular upgrade and take about 20 minutes per outlet." },
      { q: "Do you install dimmer switches?", a: "Yes, we install single-pole and 3-way dimmers compatible with LED and incandescent bulbs." },
      { q: "Can you install outdoor light fixtures?", a: "Yes, we handle porch lights, garage fixtures, and other exterior installations." },
      { q: "What if I don't have the right breaker for a new circuit?", a: "We'll assess and advise — minor panel work is within our scope for most standard jobs." },
      { q: "How do I know if my wiring is safe?", a: "Send us photos — we'll take a look and let you know if anything looks concerning before we start." },
    ],
  },
  {
    slug: "plumbing",
    icon: "🔧",
    title: "Plumbing",
    short: "Faucets, toilets, garbage disposals, and minor leak repairs.",
    hero: "No drips. No leaks.",
    description: "Reliable plumbing help for faucet and fixture replacement, toilet repairs, garbage disposal installation, shut-off valve replacement, and minor leak fixes.",
    price: "From $89",
    time: "1–2 hours",
    difficulty: "Medium",
    materials: "Fixture provided by client",
    bullets: ["Faucet and fixture replacement", "Toilet repair and replacement", "Garbage disposal install", "Minor leak repairs"],
    heroImage: "/images/plumbing-2.jpg",
    images: [
      {
        src: "/images/plumbing-1.jpg",
        title: "Kitchen Faucet Replace",
        desc: "Pull-down kitchen faucet installed with new supply lines and tested for leaks.",
        time: "1 hour",
        materials: "Plumber's tape, supply lines",
        price: "$99",
      },
      {
        src: "/images/plumbing-4.jpg",
        title: "Garbage Disposal Install",
        desc: "InSinkErator 1/2HP disposal installed with hardwired switch.",
        time: "1.5 hours",
        materials: "Mounting hardware included",
        price: "$135",
      },
      {
        src: "/images/plumbing-5.jpg",
        title: "Toilet Repair",
        desc: "Fill valve and flapper replaced, tank rebalanced, no more running water.",
        time: "45 min",
        materials: "Fill valve + flapper kit",
        price: "$89",
      },
    ],
    reviews: [
      { text: "Five stars for speed! Our disposal died and Nikita had the new one installed and tested before I could even finish my coffee. Truly efficient service and a fair price.", date: "Apr 1, 2026" },
      { text: "He arrived on time, communicated clearly, and did a great job replacing my faucet. Everything completed efficiently and professionally. Highly recommend.", date: "Mar 23, 2026" },
      { text: "I highly recommend Nikita. He did a fantastic job. He helped fix three plumbing issues I had at once!", date: "Mar 18, 2026" },
      { text: "Nikita was absolutely fantastic! He put a new cartridge in my Kohler shower and changed out two toilet bowl seats. My go-to guy!", date: "Apr 3, 2026" },
    ],
    faqs: [
      { q: "Do you handle supply lines and shut-offs?", a: "Yes, we replace supply lines, angle stops, and shut-off valves as part of the job." },
      { q: "Can you install a garbage disposal I already bought?", a: "Absolutely — just have it ready and we'll handle the full installation." },
      { q: "What if there's a bigger issue behind the wall?", a: "We'll document it and refer you to a specialist plumber if the scope goes beyond our work." },
      { q: "Can you fix a running toilet?", a: "Yes — flapper, fill valve, and flush valve replacements are quick fixes we do regularly." },
      { q: "Do you install bathroom and kitchen faucets?", a: "Yes, we install single and double-handle faucets in bathrooms, kitchens, and utility sinks." },
      { q: "Can you replace a shower cartridge?", a: "Yes — shower cartridge replacements fix temperature control issues and leaking handles. We handle most major brands." },
      { q: "Do you unclog drains?", a: "We handle simple drain clogs and slow drains. For major blockages deeper in the line, we'll refer you to a drain specialist." },
      { q: "Can you connect a new dishwasher or washing machine?", a: "Yes — appliance hookups including water supply and drain connections are within our scope." },
    ],
  },
];

export const reviews = [
  { name: "Verified Client", text: "Nikita was responsive, communicative, professional, skilled and quick. He did a quality job. I would book him again in a heartbeat.", service: "Electrical", date: "Mar 7, 2026" },
  { name: "Verified Client", text: "He arrived on time, communicated clearly, and did a great job replacing my faucet. Everything completed efficiently and professionally. Highly recommend.", service: "Plumbing", date: "Mar 23, 2026" },
  { name: "Verified Client", text: "Amazing job. Super efficient, knowledgeable, and worked with great attention to detail. Everything was done perfectly. Beyond 5 stars!", service: "Light Carpentry", date: "Jun 13, 2026" },
];

export const pricing = [
  { title: "Small Fix", price: "$69+", text: "Simple adjustment, hardware, caulking, minor repair, or quick install." },
  { title: "Standard Job", price: "$89+", text: "TV mounting, furniture assembly, smart device installation, shelving." },
  { title: "Multi-Task Visit", price: "$225+", text: "Several repairs or installs during one visit. Best value." },
];
